name: Deploy to EC2  # 이 워크플로우의 이름. GitHub Actions 탭에 표시됨

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때만 이 워크플로우가 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 사용하는 가상 머신 환경 (우분투 최신 버전)
    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 현재 저장소의 코드를 가져옴 (필수 단계)

      - name: Set up JDK
        uses: actions/setup-java@v4  # Java 빌드 환경을 설정함
        with:
          distribution: 'temurin'
          java-version: '17'  # Java 17 버전을 사용함 (Dockerfile과 일치해야 함)

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build -x test  # Gradle로 프로젝트를 빌드함. 테스트는 제외 (-x test)

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1  # ECR에 로그인. 이후 Docker push를 하기 위함
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest  # 사용할 Docker 이미지 태그 정의
          docker build -t $IMAGE_URI .  # 현재 디렉토리(.)에 있는 Dockerfile을 기준으로 이미지 빌드
          docker push $IMAGE_URI  # 빌드한 이미지를 ECR에 push (업로드)

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat <<EOF > .env
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}
            EOF

            # ECR 로그인 추가 
            aws ecr get-login-password --region ap-northeast-2 | \
            docker login --username AWS --password-stdin 888042016323.dkr.ecr.ap-northeast-2.amazonaws.com
            
            docker network create rssol-net || true

            docker stop redis || true && docker rm redis || true
            docker run -d \
              --name redis \
              --network rssol-net \
              -p 6379:6379 \
              redis:latest # redis 이미지가 로컬에 없으면 Docker Hub에서 자동으로 pull함.

            docker stop app || true && docker rm app || true
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
            docker run -d \
              --name app \
              --network rssol-net \
              --env-file .env \
              -p 8080:8080 \
              -e "JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true" \
              ${{ secrets.ECR_REPOSITORY }}:latest
